/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica02isw;

import java.awt.Label;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Erick
 */
public class VistaPrincipal extends javax.swing.JFrame {
    ControladorPelea ctrlPelea;
    ControladorVista ctrlVista;
    VistaRankings vstRankings;
 

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() throws IOException {
        ctrlVista = new ControladorVista(ctrlPelea);
        ctrlPelea = new ControladorPelea(ctrlVista);
        vstRankings = new VistaRankings();
        initComponents();
    }

    public void actualizarLog(){
    System.out.println(ctrlVista.getLog());    
    consolaJuego.setText(ctrlVista.getLog());
    }
    
    public void actualizarHP(){
        barraHPPlayer.setValue((int)ctrlPelea.getSuperHeroePlayer().getVida());
        barraHPPlayer.setString(barraHPPlayer.getMaximum()+"/"+(int)ctrlPelea.getSuperHeroePlayer().getVida());
        barraHPPlayer.updateUI();
        
        barraHPCPU.setValue((int)ctrlPelea.getSuperHeroeCPU().getVida());
        barraHPCPU.setString(barraHPCPU.getMaximum()+"/"+(int)ctrlPelea.getSuperHeroeCPU().getVida());
        barraHPCPU.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJuego = new javax.swing.JButton();
        btnPelea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consolaJuego = new javax.swing.JTextArea();
        btnGolpe = new javax.swing.JToggleButton();
        btnPatada = new javax.swing.JToggleButton();
        btnAtaqueEsp = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imgCPU = new javax.swing.JLabel();
        imgJ1 = new javax.swing.JLabel();
        lbNombreJugador = new javax.swing.JLabel();
        lbPlHeroe = new javax.swing.JLabel();
        lbCPUHeroe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbTiempo = new javax.swing.JLabel();
        btnCambiarJugador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        barraHPPlayer = new javax.swing.JProgressBar();
        barraHPCPU = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica #2 - Pelea de Super Heroes");

        btnJuego.setText("INICIAR JUEGO");
        btnJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoActionPerformed(evt);
            }
        });

        btnPelea.setText("INICIAR PELEA");
        btnPelea.setEnabled(false);
        btnPelea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeleaActionPerformed(evt);
            }
        });

        consolaJuego.setColumns(20);
        consolaJuego.setRows(5);
        consolaJuego.setEnabled(false);
        jScrollPane1.setViewportView(consolaJuego);

        btnGolpe.setText("GOLPE");
        btnGolpe.setEnabled(false);
        btnGolpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolpeActionPerformed(evt);
            }
        });

        btnPatada.setText("PATADA");
        btnPatada.setEnabled(false);
        btnPatada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatadaActionPerformed(evt);
            }
        });

        btnAtaqueEsp.setText("ATAQUE ESPECIAL");
        btnAtaqueEsp.setEnabled(false);
        btnAtaqueEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueEspActionPerformed(evt);
            }
        });

        jLabel1.setText("JUGADOR:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("VS");
        jLabel2.setEnabled(false);

        imgCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/noimageCPU.png"))); // NOI18N
        imgCPU.setText("???");
        imgCPU.setEnabled(false);

        imgJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/noimageP1.png"))); // NOI18N
        imgJ1.setText("???");
        imgJ1.setEnabled(false);

        lbPlHeroe.setText("<player>");

        lbCPUHeroe.setText("<cpu>");

        jLabel3.setText("TIEMPO:");

        lbTiempo.setText("0");

        btnCambiarJugador.setText("CAMBIAR JUGADOR");
        btnCambiarJugador.setEnabled(false);

        jButton2.setText("RANKINGS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("HP: ");

        jLabel5.setText("HP: ");

        jLabel6.setText("ID: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJuego)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPelea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCambiarJugador))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(258, 258, 258)
                                                .addComponent(lbPlHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(96, 96, 96)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAtaqueEsp)
                                    .addComponent(btnGolpe)
                                    .addComponent(btnPatada)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbCPUHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barraHPPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barraHPCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGolpe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPatada)
                                        .addGap(13, 13, 13)
                                        .addComponent(btnAtaqueEsp))
                                    .addComponent(imgJ1)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnCambiarJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPlHeroe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barraHPPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(imgCPU))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(lbCPUHeroe)
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(barraHPCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(25, 25, 25))
                            .addComponent(jScrollPane1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnPelea)
                    .addComponent(btnJuego))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoActionPerformed

        try {
           ctrlVista.obtenerJugador();
           ctrlVista.obtenerSeleccion();
           ctrlPelea.obtenerHeroes();
           actualizarLog();
           
           lbNombreJugador.setVisible(true);
           lbPlHeroe.setVisible(true);
           lbCPUHeroe.setVisible(true);
        
           consolaJuego.setVisible(true);
           actualizarLog();
           actualizarHP();
           imgJ1.setEnabled(true);
           imgCPU.setEnabled(true);        
           btnPelea.setEnabled(true);
           
           imgJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ctrlPelea.getSuperHeroePlayer().getRutaImg())));
           imgCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource(ctrlPelea.getSuperHeroeCPU().getRutaImg())));
           
           barraHPPlayer.setMaximum((int)ctrlPelea.getSuperHeroePlayer().getVida());
           barraHPPlayer.setString(barraHPPlayer.getMaximum()+"/"+(int)ctrlPelea.getSuperHeroePlayer().getVida());
           barraHPPlayer.setMinimum(0);
           barraHPPlayer.setStringPainted(true);
           
           barraHPCPU.setMaximum((int)ctrlPelea.getSuperHeroeCPU().getVida());
           barraHPCPU.setString(barraHPCPU.getMaximum()+"/"+(int)ctrlPelea.getSuperHeroeCPU().getVida());
           barraHPCPU.setMinimum(0);
           barraHPCPU.setStringPainted(true);
           
           lbNombreJugador.setText(ctrlVista.getNombreJugador());
           lbID.setText(String.valueOf(ctrlPelea.getJugador().getId()));
           lbPlHeroe.setText(ctrlPelea.getNombreHeroePlayer());
           lbCPUHeroe.setText(ctrlPelea.getNombreHeroeCPU());
          // consolaJuego.setText(ctrlVista.getLog());
           btnJuego.setEnabled(false);
            
        } catch (IOException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnJuegoActionPerformed

    private void btnPeleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeleaActionPerformed
ctrlPelea.iniciarPelea();
btnGolpe.setEnabled(true);
btnPatada.setEnabled(true);
btnAtaqueEsp.setEnabled(true);
btnPelea.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnPeleaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
vstRankings.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGolpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolpeActionPerformed
ctrlPelea.registrarAtaque(0);
actualizarHP();// TODO add your handling code here:
    }//GEN-LAST:event_btnGolpeActionPerformed

    private void btnPatadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatadaActionPerformed
ctrlPelea.registrarAtaque(1);
actualizarHP();// TODO add your handling code here:
    }//GEN-LAST:event_btnPatadaActionPerformed

    private void btnAtaqueEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueEspActionPerformed
ctrlPelea.registrarAtaque(2);
actualizarHP();// TODO add your handling code here:
    }//GEN-LAST:event_btnAtaqueEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraHPCPU;
    private javax.swing.JProgressBar barraHPPlayer;
    private javax.swing.JToggleButton btnAtaqueEsp;
    private javax.swing.JButton btnCambiarJugador;
    private javax.swing.JToggleButton btnGolpe;
    private javax.swing.JButton btnJuego;
    private javax.swing.JToggleButton btnPatada;
    private javax.swing.JButton btnPelea;
    private javax.swing.JTextArea consolaJuego;
    private javax.swing.JLabel imgCPU;
    private javax.swing.JLabel imgJ1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCPUHeroe;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNombreJugador;
    private javax.swing.JLabel lbPlHeroe;
    private javax.swing.JLabel lbTiempo;
    // End of variables declaration//GEN-END:variables
}
